apiVersion: v1
kind: Service
metadata:
  name: {{ include "msa-helpchart.fullname" . }}
  labels:
    {{- include "msa-helpchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "msa-helpchart.selectorLabels" . | nindent 4 }}
