apiVersion: v1
kind: Pod
metadata:
  name: 146pod
spec:
  containers:
    - name: pv-pod
      image: nginx
      volumeMounts:
      - name: mypd
        mountPath: "/var/wwww/html"
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: 146pvc
